#!/bin/sh
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000

# export PATH="$HOME/.local/bin":$PATH  # already exists
# export MANPAGER='nvim +Man!'
# export MANWIDTH=999

# Completion #
eval "$(fnm env)"
eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"
